services:
  bifm-bypass:
    public: true
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 32333
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
      limits:
        cpu: 1000m
        memory: 2000Mi